# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmUNS1o4TajzUrr-T96_EjGcixmOGaY7
"""

!pip install gradio pillow numpy opencv-python-headless

import cv2
import numpy as np
from PIL import Image

def analyze_skin_image(image):
    img = np.array(image)
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    # 1. symmetry score
    h, w = gray.shape
    left = gray[:, :w//2]
    right = cv2.flip(gray[:, w//2:], 1)
    diff = np.abs(left.astype(float) - right.astype(float))
    symmetry = 100 - (np.mean(diff) / 255 * 100)

    # 2. edge irregularity
    edges = cv2.Canny(gray, 50, 150)
    edge_density = np.sum(edges > 0) / (h * w) * 100

    # 3. color variation
    r, g, b = cv2.split(img)
    color_var = (np.std(r) + np.std(g) + np.std(b)) / 3

    # scoring
    warnings = []
    risk = 0

    if symmetry < 70: risk += 25; warnings.append("Asymmetrical, irregular shape detected")
    if edge_density > 12: risk += 25; warnings.append("Irregular borders, edges look uneven")
    if color_var > 55: risk += 25; warnings.append("High color variation, multiple tones present")

    if risk >= 50:
        verdict = "SEE A DOCTOR"
    elif risk >= 25:
        verdict = "MONITOR, recheck in 2 weeks"
    else:
        verdict = "LIKELY BENIGN"

    return verdict, risk, warnings, symmetry, edge_density, color_var

import gradio as gr

def medscan(image):
    if image is None:
        return "Please upload an image.", "", "", "", ""

    verdict, risk, warnings, sym, edges, color = analyze_skin_image(image)

    # Fixed the unterminated string literal and added newline for join
    warning_text = "\n".join(f"• {w}" for w in warnings) if warnings else "• No warning signs detected"
    stats = f"Symmetry: {sym:.1f}% | Edge density: {edges:.1f}% | Color variation: {color:.1f}"

    return verdict, f"Risk Score: {risk}/75", warning_text, stats

demo = gr.Interface(
    fn=medscan,
    inputs=gr.Image(type="pil", label="Upload skin image"),
    outputs=[
        gr.Textbox(label="VERDICT"),
        gr.Textbox(label="Risk"),
        gr.Textbox(label="Warning Signs"),
        gr.Textbox(label="Stats")
    ],
    title="MedScan Lite v0.1",
    # Fixed the multi-line string for description using triple quotes
    description="""A.I. Biotech, Prototype skin analyzer. Upload an image for basic risk assessment.

⚠️ NOT a medical device. See a doctor for real concerns."""
)

demo.launch(share=True)